### ISSUE TITLE
在Release模式下编译，会报错：Error: symbol `FLAGLABLE' is already defined

### ISSUE THREAD

**Issue by MaryBurner** [luchenxu73/air32f103_gcc_clion_template#2]
编译命令：cmake -DCMAKE_BUILD_TYPE=Release .. &&  make
编译结果：
![image](https://github.com/luchenxu73/air32f103_gcc_clion_template/assets/149713912/5bb6b621-c4a3-48d2-8e5f-fb66dc27d2cf)
希望能修复。

**Comment by luchenxu73** [comment]
问题已修复。
在`air32f10x_flash.c`中对`void SetStrt(void)`添加`__attribute__((noinline)) `修饰。
即修改为`__attribute__((noinline))  void SetStrt(void)`即可。
